events:
  # List of events to monitor and start automatically
  # Format: event_id with cron schedule
  example_event:
    event_id: "1234567890123456789"  # Replace with actual event ID
    cron: "0 20 * * 5"  # Every Friday at 8 PM
    enabled: false

  # Add more events here
  # weekly_meeting:
  #   event_id: "0987654321098765432"
  #   cron: "0 14 * * 1"  # Every Monday at 2 PM
  #   enabled: true

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

bot:
  command_prefix: "!"
  status: "Automating your events"